const types = {
    ALERT: 'ALERT',
    REMOVE_ALERT: 'REMOVE_ALERT',
    SET_DYNAMICS_STATE: 'SET_DYNAMICS_STATE',
    TOGGLE_OPEN_OBJECT_MODAL: 'TOGGLE_OPEN_OBJECT_MODAL',
    TOGGLE_EXPANDED: 'TOGGLE_EXPANDED'
};

export default types;