name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chromeExtension
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
            file_name: ./chromeExtension/.env
        env:
            INPUT_ENVKEY_FATHOM_SITE_ID: ${{ secrets.FATHOM_SITE_ID }}
            INPUT_ENVKEY_HONEYBADGER_API_KEY: ${{ secrets.HONEYBADGER_API_KEY }}
            INPUT_ENVKEY_SUMO_LOGIC_COLLECTOR: ${{ secrets.SUMO_LOGIC_COLLECTOR }}
            INPUT_ENVKEY_DISABLE_LOGGING: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 14
      - name: Install App Dependencies
        run: yarn --frozen-lockfile
      - name: Build App
        run: yarn prod
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: chromeExtension/dist/extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
